### ISSUE TITLE
candidate Register: Email without @

### ISSUE THREAD

**Issue by Makabata** [harambee-sa/Defects#11]
![mobisite](https://user-images.githubusercontent.com/29088902/27322711-6be57ad8-559f-11e7-8566-18a6255f95f7.png)
Prompts the error message, but keeps loading (would expect it to go back to page1 and allow the candidate to input the correct email address???)

**Comment by omokwena** [comment]
It has been sorted out. on the next deployment it the issue will be fixed.

**Comment by CharleenN** [comment]
Retested.  Isssue has been resolved.  Closing
