### ISSUE TITLE
Mobisite - Apply: Issue with response time after clicking on confirm

### ISSUE THREAD

**Issue by CharleenN** [harambee-sa/Defects#13]
Mobisite - 
![response time_loading_apply_20 june 2017](https://user-images.githubusercontent.com/29141509/27323177-eadb87e6-55a0-11e7-910a-da4b5eba74ed.png)
Apply - Issue with response time after clicking on confirm (have waited for 5 minutes) Page says "loading" but does not respond after that

In the e-mail address field, only one numeric character was captured and the terms and conditions have not been selected upon confirming

**Comment by omokwena** [comment]
This issue is related to @Makabata  issue he created earlier. so this has been resolved. in the next deployment it will be gone.

**Comment by CharleenN** [comment]
@omokwena - Thank you.  Please let me know once the deployment is done so I can retest

**Comment by CharleenN** [comment]
Issue has been retested.  Closing
