### ISSUE TITLE
Mobisite - Join Harambee network: timeout when creating password

### ISSUE THREAD

**Issue by CharleenN** [harambee-sa/Defects#15]
As a candidate, when creating a password, leave the password and confirm password fields blank

When clicking on "join harambee", a HTTP 404 error occurs

**Comment by omokwena** [comment]
sorted this issue out for now. So now they can leave it blank but will display an error by the password and confirm password.

**Comment by CharleenN** [comment]
Retested - Issue has been resolved.  Closing
