### ISSUE TITLE
Existing User Call Me button does not work

### ISSUE THREAD

**Issue by oscarsgit** [harambee-sa/Defects#21]
Clicking on the Call me button results in a blank screen on the Registration Page

Steps to reproduce:
1. On the registration page, create a candidate profile with an ID Number that already exists but all the         other fields are different
2. Click Confirm button
3. Upon receiving the error message, click on the Call Me button

See screenshots attached
![image](https://user-images.githubusercontent.com/10419308/28010110-1ac84f3a-655e-11e7-849e-b7afa6e58596.png)

**Error**
![image](https://user-images.githubusercontent.com/10419308/28010136-337362f4-655e-11e7-8e27-27abc09a840e.png)

**Comment by omokwena** [comment]
Fixed the error message
