### ISSUE TITLE
Forgot Username: HTTP 404 error when submitting an ID number of a candidate that has not been registered

### ISSUE THREAD

**Issue by CharleenN** [harambee-sa/Defects#8]
Forgot username:  HTTP 404 error upon submitting when entering and ID number of a candidate that has not been registered

**Comment by CharleenN** [comment]
@omokwena - Re-opening this issue as it is re-occurring

**Comment by omokwena** [comment]
I have been able to catch the bug and fix the issue.

**Comment by CharleenN** [comment]
@omokwena thank you.  Please let me know once deployed so I can retest

**Comment by CharleenN** [comment]
Retested.  Issue has been resolved.  Closing
